### PR TITLE
Add ET and PS scores logic

### PR DESCRIPTION
**Pull request by trouni**
Somehow this crashes the ruby interpreter for me... Could you give it a try?

### CODE REVIEW

**Comment by dmbf29** [comment]
on a specific file?

**Comment by trouni** [comment]
When running the job

**Comment by trouni** [comment]
It doesn't crash consistently though, a bit weird.
rails_c

**Comment by trouni** [comment]
Fixed(?) this:
```
ActionView::Template::Error (undefined method `>' for nil:NilClass):
    1: json.partial! @user
    2: json.points @user.score(@competition) if @competition
app/models/match.rb:40:in `winner_side'
app/models/prediction.rb:12:in `correct?'
app/models/user.rb:27:in `score'
app/views/v1/users/show.json.jbuilder:2
```

**Comment by dmbf29** [comment]
yes can confirm. I can view other people's picks now. ℹ️ games still not displaying correctly but i guess you know that

**Review by dmbf29 — APPROVED** [review]

**Pull request merged**
