### PR TITLE
Feature: Implement Match and Prediction instance methods

### LINKED ISSUE #15: Create instance methods for Match/Prediction
- [ ] `Match#winner`
- [ ] `Match#round`
- [ ] `Prediction#correct?`

### PR DESCRIPTION
**Pull request by trouni**
Resolves #15 

- [x] Fix null constraint on `group_id`
- [x] Fix missing `round_id` on `matches`
- [x] Add `round`/`group` validation
- [x] Add custom reader for `round`
- [x] Add `Match#winner` and `Prediction#correct?` methods

### CODE REVIEW

**Review by dmbf29 — COMMENTED** [review]
what's this `super` doing?

```
def round
  super || group&.round
end  
```

**Comment by trouni** [comment]
`super` calls the default `attr_reader`. We can't just call `round` inside of the `round` method, otherwise you'd get an infinite loop. In this case, `super` basically checks for the `round` using the `round_id`, not the custom reader.

**Comment by dmbf29** [comment]
oh snap. so when you override an instance method, super will call the previously made one on the same level??

**Comment by trouni** [comment]
I think it actually calls the one from the parent (which gets created when we define `belongs_to :round`) since there was technically no `round` method in this child class before. So the parent `round` method is defined by `ActiveRecord::Base` and we're just referring to that one when calling `super`.

**Comment by dmbf29** [comment]
ahhhhh right right right. that method is coming from AR derrrrrrr

**Review by dmbf29 — APPROVED** [review]
sexy

**Pull request merged**
