### PR TITLE
World cup setup

### PR DESCRIPTION
**Pull request by dmbf29**
Created a rake task to setup the World Cup groups and teams. 

No matches yet. Need an API for that.

### CODE REVIEW

**Comment by dmbf29** [comment]
When deployed, we'll need to run
```
heroku run rails competition:world_cup
heroku run rails team:add_flag
```

**Comment by dmbf29** [comment]
Screen Shot 2022-11-08 at 22 39 07

**Comment by dmbf29** [comment]
For some reason, when Vue is asking for the competition matches in the `matches_controller`, it’s still sending `competition_id: '1'` which shouldn’t be the case so I hard-coded the last one `@competition = Competition.order(id: :desc).first`

**Comment by trouni** [comment]
I saw you reverted to the original version, did it end up working?

**Comment by dmbf29** [comment]
Yes. Reverted the matches_controller to what it was before and everything 👌

**Review by trouni — APPROVED** [review]

**Pull request merged**
