### PR TITLE
added a daily job to check for day events

### PR DESCRIPTION
**Pull request by dmbf29**
Will set `ScheduleDailyTasksJob` to schedule updates for all of the matches that day

### CODE REVIEW

**Review by trouni — APPROVED** [review]
Awesome 👏 

Does the MatchStartedJob run only once then? Does it call itself back a bit later if the match still hasn't started when making that API call?

Like, I'm thinking that if a game's kickoff get slightly delayed and the job runs right on the scheduled kickoff time, it might still appear as upcoming.

**Comment by dmbf29** [comment]
So actually since I'm not 100% sure how the API work when a match starts yet, we're setting it to `started` based only on the kickoff_time

**Comment by trouni** [comment]
Ok sounds good!

**Comment by dmbf29** [comment]
We should know more about in 17 minutes 🤞

**Pull request merged**
