### PR TITLE
Pundit

### LINKED ISSUE #3: Pundit
- [ ] policy creation

### PR DESCRIPTION
**Pull request by dmbf29**
Closes #3 

Created this branch off the seeds. Merge this one after that #8  

simple one. installed the gem and added error catching in application controller

One thing that needs to be changed still for Devise
```
# ==> Mailer Configuration
# Configure the e-mail address which will be shown in Devise::Mailer,
# note that it will be overwritten if you use your own mailer class
# with default "from" parameter.
config.mailer_sender = 'please-change-me-at-config-initializers-devise@example.com'

### CODE REVIEW

**Review by trouni — APPROVED** [review]
FYI, I have (at least temporarily) change the branch into which we are merging this PR to the `seeds` branch. Not sure what is best practice when we branch off non merged branches, but this allows me to narrow down the diff only to the changes you've added compared to the `seeds` branch.
Pundit_by_dmbf29_·_Pull_Request__9_·_dmbf29_predictor-api

**Comment by dmbf29** [comment]
yeah actually i was going to merge it into `seeds` but i wasn't 100% sure what would happen when `seeds` gets merged first. was assuming it'd just be `main` after that but 🤷‍♀️

**Comment by trouni** [comment]
Not sure either, it may also break? I guess in theory you should merge this one into `seeds` first? But that's a bit strange for the flow. Maybe let's try to merge seeds first and see what happens?

**Comment by dmbf29** [comment]
yeah good idea. i'll do that now.

**Comment by dmbf29** [comment]
Screen Shot 2021-04-08 at 12 43 02

Yep okay cool. it just gets moved to main. Good to know.

**Comment by trouni** [comment]
Perfect, good to know indeed that's pretty useful!

**Pull request merged**
