### PR TITLE
User photo

### PR DESCRIPTION
**Pull request by dmbf29**
Added photo to a user. Need this for avatar on Leaderboard

I wasn't 💯 on this:
```
if params[:user][:photo_url]
  file = URI.open(params[:user][:photo_url])
  @user.photo.attach(io: file, filename: 'profile.png', content_type: 'image/png')
  render :show
elsif @user.update(prediction_params)
    # ...
 ```
 
 but that's the best i could do for now

### CODE REVIEW

**Comment by trouni** [comment]
Hmmmm... I think you are doubling up on the upload here.

All ActiveStorage normally does is store the key for the photo on Cloudinary, so that it can rebuild the url of the image. Basically just a convenient way to upload a file and at the same time capture and store the Cloudinary key (=url) in your DB.

In our case here, the Cloudinary widget in the FE is already handling the image upload. It returns the url of the uploaded image, so all you need to do is to create an `avatar_url` attribute to the user and store the url as a string.

Not sure if it makes sense, but in other words, at the moment, you're uploading the image to Cloudinary via the FE, getting the Cloudinary url from that first upload and sending it to the BE, which then re-downloads the image from Cloudinary and stores it on another Cloudinary instance.

**Comment by dmbf29** [comment]
crap. yeah...

**Comment by dmbf29** [comment]
It made more sense to save the key instead of the url.We can get more image options with the key and cloudinary components.

**Review by trouni — APPROVED** [review]
Cool! 👍

**Pull request merged**
