### PR TITLE
Memberships

### PR DESCRIPTION
**Pull request by dmbf29**
user can join with a unique token instead of manually entering a password

wasn't 100% sure on the route since technically the `join/:password` route will be in the front-end routes im assuming

### CODE REVIEW

**Comment by dmbf29** [comment]
Screen Shot 2021-04-24 at 19 48 00

**Review by trouni — COMMENTED** [review]
I think we should refactor the jbuilder views to use partials to stay consistent.
The `_prediction.json.jbuilder` partial already exists from one of the latest PRs, but we should create the `_membership.json.jbuilder` partial and use it for the `show`?

**Comment by dmbf29** [comment]
>  we should create the _membership.json.jbuilder partial and use it for the show
Can you explain this a little bit more? Not sure I'm following

**Comment by trouni** [comment]
If you look at these two files, it should clarify things:
https://github.com/dmbf29/predictor-api/tree/main/app/views/v1/predictions

The idea is to put the content of the `memberships/show.json` in a `_membership` partial, then call it in the `show`. This makes the `_membership` fragment reusable in other views without having to duplicate its content.

**Comment by dmbf29** [comment]
ahhhhh okay okay 👌

**Comment by dmbf29** [comment]
@trouni updated.

**Review by trouni — APPROVED** [review]
👍

**Pull request merged**
